name: python2
channels: !!python/tuple
- defaults
dependencies:
- affine=2.0.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- beautifulsoup4=4.5.3=py27_0
- bleach=1.5.0=py27_0
- bokeh=0.11.1=py27_0
- cairo=1.14.8=0
- click=6.7=py27_0
- click-plugins=1.0.3=py27_0
- cligj=0.4.0=py27_0
- cloudpickle=0.1.1=py27_0
- configparser=3.5.0=py27_0
- curl=7.49.0=1
- cycler=0.10.0=py27_0
- cython=0.23.5=py27_0
- dbus=1.10.10=0
- decorator=4.0.11=py27_0
- dill=0.2.5=py27_0
- entrypoints=0.2.2=py27_1
- enum34=1.1.6=py27_0
- expat=2.1.0=0
- fiona=1.7.0=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- futures=3.0.5=py27_0
- geos=3.5.0=0
- geotiff=1.4.1=0
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.6.0=np111py27_2
- hdf4=4.2.12=0
- hdf5=1.8.17=1
- html5lib=0.999=py27_0
- icu=54.1=0
- ipykernel=4.5.2=py27_0
- ipython=4.2.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_1
- jbig=2.1=0
- jinja2=2.9.4=py27_0
- jpeg=8d=2
- jsonschema=2.5.1=py27_0
- jupyter_client=4.4.0=py27_0
- jupyter_core=4.3.0=py27_0
- kealib=1.4.6=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgdal=2.1.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libnetcdf=4.4.1=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libxcb=1.12=1
- libxml2=2.9.4=0
- llvmlite=0.15.0=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.3=np111py27_1
- mistune=0.7.3=py27_0
- mkl=11.3.3=0
- mpmath=0.19=py27_1
- munch=2.1.0=py27_0
- nbconvert=5.1.1=py27_0
- nbformat=4.2.0=py27_0
- networkx=1.11=py27_0
- nomkl=1.0=0
- notebook=4.3.1=py27_0
- numba=0.30.1=np111py27_0
- numexpr=2.6.2=np111py27_nomkl_0
- numpy=1.11.3=py27_nomkl_0
- openblas=0.2.19=0
- openssl=1.0.2k=0
- pandas=0.19.2=np111py27_1
- pandocfilters=1.4.1=py27_0
- path.py=10.1=py27_0
- pathlib2=2.2.0=py27_0
- patsy=0.4.1=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=3.4.2=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- proj4=4.9.2=0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2016.10=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=2
- rasterio=0.36.0=np111py27_0
- readline=6.2=2
- requests=2.13.0=py27_0
- scandir=1.4=py27_0
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.18.1=np111py27_nomkl_1
- scipy=0.17.1=np111py27_1
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- shapely=1.5.16=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- snuggs=1.4.0=py27_0
- sqlalchemy=1.0.13=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.6.1=np111py27_1
- sympy=1.0=py27_0
- terminado=0.6=py27_0
- testpath=0.3=py27_0
- tk=8.5.18=0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- vincent=0.4.4=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_0
- xerces-c=3.1.4=0
- xlrd=1.0.0=py27_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-core==4.3.0

